ci:
  autofix_prs: false
  autoupdate_schedule: 'quarterly'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
        # Prevent giant files from being committed
      - id: check-added-large-files
        # Check whether files parse as valid Python
      - id: check-ast
        # Check for files that contain merge conflict strings
      - id: check-merge-conflict
        # Attempts to load all TOML files to verify syntax
      - id: check-toml
        # Attempts to load all yaml files to verify syntax
      - id: check-yaml
        # Check for debugger imports and py37+ breakpoint() calls in python source
      - id: debug-statements
        # Makes sure files end in a newline and only a newline
      - id: end-of-file-fixer
        # Replaces or checks mixed line ending
      - id: mixed-line-ending
        # Protect specific branches from direct checkins (main)
      - id: no-commit-to-branch
        # Trims trailing whitespace
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/flake8
    rev: "3.9.2"
    hooks:
      - id: flake8
  - repo: https://github.com/codespell-project/codespell
    rev: "v2.2.2"
    hooks:
    - id: codespell
      types_or: [python, markdown, rst]
      additional_dependencies: [tomli]
  - repo: https://github.com/aio-libs/sort-all
    rev: "v1.2.0"
    hooks:
      - id: sort-all
        types: [file, python]
  - repo: https://github.com/PyCQA/isort
    rev: "5.12.0"
    hooks:
      - id: isort
        types: [file, python]
        args: [--filter-files]
  - repo: https://github.com/psf/black
    rev: "23.1.0"
    hooks:
      - id: black
        types: [file, python]
        args: [--config=./pyproject.toml]
