ci:
  autofix_prs: false
  autoupdate_schedule: 'quarterly'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v6.0.0"
    hooks:
        # Prevent giant files from being committed
      - id: check-added-large-files
        # Check whether files parse as valid Python
      - id: check-ast
        # Check for files that contain merge conflict strings
      - id: check-merge-conflict
        # Attempts to load all TOML files to verify syntax
      - id: check-toml
        # Attempts to load all yaml files to verify syntax
      - id: check-yaml
        # Check for debugger imports and py37+ breakpoint() calls in python source
      - id: debug-statements
        # Makes sure files end in a newline and only a newline
      - id: end-of-file-fixer
        # Replaces or checks mixed line ending
      - id: mixed-line-ending
        # Protect specific branches from direct checkins (main)
      - id: no-commit-to-branch
        # Trims trailing whitespace
      - id: trailing-whitespace
  - repo: https://github.com/codespell-project/codespell
    rev: "v2.4.1"
    hooks:
    - id: codespell
      types_or: [python, markdown, rst]
      additional_dependencies: [tomli]
  - repo: https://github.com/aio-libs/sort-all
    rev: "v1.3.0"
    hooks:
      - id: sort-all
        types: [file, python]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.13.3'
    hooks:
    - id: ruff
      args: [--fix]
