# Circle CI configuration file
# https://circleci.com/docs/

version: 2


###########################################
# Define some common steps as YAML anchors.
#

apt-run:  &apt-install
  name: Install apt packages
  command: |
    apt-get -qq update
    apt-get install -y \
      gcc \
      g++ \
      make

env-run:  &env-setup
  # Create the basic testing environment
  # Mixing conda-forge and defaults in root is a recipe for trouble, so create
  # a separate environment.
  name: Setup conda environment
  command: |
    # Update conda to fix https://github.com/conda/conda/issues/6811
    conda install -n base conda
    conda config --set always_yes yes --set changeps1 no --set show_channel_urls yes
    conda create -n test-environment python=$PYTHON_VERSION
    conda config --add channels conda-forge

deps-run: &deps-install
  name: Install Python dependencies
  command: |
    source activate test-environment
    conda install --quiet \
        numpy \
        matplotlib \
        scipy \
        cython \
        pillow \
        proj4 \
        pyshp \
        shapely \
        six \
        requests \
        pyepsg \
        owslib \
        pykdtree \
        $EXTRA_PACKAGES \
        --file docs/doc-requirements.txt
    conda list

cp-run: &cp-install
  name: Install Cartopy
  command: |
    source activate test-environment
    pip install --no-build-isolation --no-deps -ve .

doc-run: &doc-build
  name: Build documentation
  command: |
    source activate test-environment
    make html
  working_directory: docs


##########################################
# Here is where the real jobs are defined.
#

jobs:
  docs-python3:
    docker:
      - image: continuumio/miniconda3:latest
    steps:
      - checkout

      - run: *apt-install
      - run:
          <<: *env-setup
          environment:
            PYTHON_VERSION: 3
      - run: *deps-install
      - run: *cp-install

      - run: *doc-build

      - store_artifacts:
          path: docs/build/html

      - run:
          name: "Built documentation is available at:"
          command: echo "${CIRCLE_BUILD_URL}/artifacts/${CIRCLE_NODE_INDEX}/${CIRCLE_WORKING_DIRECTORY/#\~/$HOME}/docs/build/html/index.html"

  docs-python2:
    docker:
      - image: continuumio/miniconda:latest
    steps:
      - checkout

      - run: *apt-install
      - run:
          <<: *env-setup
          environment:
            PYTHON_VERSION: 2
            EXTRA_PACKAGES: "futures"
      - run: *deps-install
      - run: *cp-install

      - run: *doc-build

      - store_artifacts:
          path: docs/build/html

      - run:
          name: "Built documentation is available at:"
          command: echo "${CIRCLE_BUILD_URL}/artifacts/${CIRCLE_NODE_INDEX}/${CIRCLE_WORKING_DIRECTORY/#\~/$HOME}/docs/build/html/index.html"


#########################################
# Defining workflows gets us parallelism.
#

workflows:
  version: 2
  build:
    jobs:
      - docs-python3
      - docs-python2
